name : Warp
main : warp.Warp
version : 1.0-SNAPSHOT
author : Organic
api : [1.0.0]
  
permissions : 
 addwarp.cmd :
  default : OP
 delwarp.cmd : 
  default : OP
 warplist.cmd : 
  default : true
 warp.cmd : 
  default : true
